### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Jnllee** [Marsaaaaaaa/python_ow2_paste#2]
C:\Users\ngcli\Desktop\python_ow2_paste-main>python main.py
Traceback (most recent call last):
  File "C:\Users\ngcli\Desktop\python_ow2_paste-main\main.py", line 2, in <module>
    from grabber import *
  File "C:\Users\ngcli\Desktop\python_ow2_paste-main\grabber.py", line 15
    from ClassLibrary1 import Class1
    ^
SyntaxError: invalid syntax

**Comment by Marsaaaaaaa** [comment]
if you have set up everything correctly the script (main.py) should run even with the error
