### ISSUE TITLE
help ^_^ 

### ISSUE THREAD

**Issue by 04x98** [Marsaaaaaaa/python_ow2_paste#3]
"C:\Program Files\Python39\python.exe" C:/Users/xxxx/Downloads/Compressed/python_ow2_paste-main/python_ow2_paste-main/main.py
Traceback (most recent call last):
  File "C:\Users\xxxx\Downloads\Compressed\python_ow2_paste-main\python_ow2_paste-main\main.py", line 2, in <module>
    from grabber import *
  File "C:\Users\xxxx\Downloads\Compressed\python_ow2_paste-main\python_ow2_paste-main\grabber.py", line 14, in <module>
    clr.AddReference('C:\\Users\\xxxx\\Downloads\\Compressed\\python_ow2_paste-main\\python_ow2_paste-main\\DLL\\ClassLibrary1\\ClassLibrary1.dll')
AttributeError: module 'clr' has no attribute 'AddReference'

**Comment by HeatherBeryl** [comment]
print("Hello Python World!")after this commit in sublime text but can not have reply

**Comment by Marsaaaaaaa** [comment]
have you installed the module pythonnet
